baseurl = "/research"
languageCode = "utf-8"
title = "MVP Tutorial"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishdir = "docs"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Seminar"
    url = "/seminar/"
    weight = 2

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [MVP Tutorial](http://mvp.yonsei.ac.kr) 2017"
